// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  entries: [
    {
      idx: 0,
      when: 1773376221848,
      tag: "0000_useful_la_nuit",
      breakpoints: true,
    },
  ],
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`branches\` (
	\`branch_name\` text PRIMARY KEY NOT NULL,
	\`commit_sha\` text NOT NULL,
	\`parent_branch\` text,
	\`tracked_in_stack\` integer DEFAULT 0 NOT NULL,
	\`diff_stat\` text,
	\`has_unpushed\` integer DEFAULT 0 NOT NULL,
	\`conflicts_with_main\` integer DEFAULT 0 NOT NULL,
	\`first_seen_at\` integer,
	\`last_seen_at\` integer,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`repo_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`remote_url\` text NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`task_index\` (
	\`task_id\` text PRIMARY KEY NOT NULL,
	\`branch_name\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
`,
  } as const,
};
