export {
  LiveAcpConnection,
  ProcessTerminalSession,
  SandboxAgent,
  SandboxAgentError,
  SandboxDestroyedError,
  Session,
  UnsupportedPermissionReplyError,
  UnsupportedSessionCategoryError,
  UnsupportedSessionConfigOptionError,
  UnsupportedSessionValueError,
} from "./client.ts";

export { AcpRpcError } from "acp-http-client";

export { buildInspectorUrl } from "./inspector.ts";
export { DesktopStreamSession } from "./desktop-stream.ts";
export type {
  DesktopStreamConnectOptions,
  DesktopStreamErrorStatus,
  DesktopStreamReadyStatus,
  DesktopStreamStatusMessage,
} from "./desktop-stream.ts";

export type {
  SandboxAgentHealthWaitOptions,
  AgentQueryOptions,
  DesktopStreamSessionOptions,
  ProcessLogFollowQuery,
  ProcessLogListener,
  ProcessLogSubscription,
  ProcessTerminalConnectOptions,
  ProcessTerminalSessionOptions,
  ProcessTerminalWebSocketUrlOptions,
  SandboxAgentConnectOptions,
  SandboxAgentStartOptions,
  SessionCreateRequest,
  SessionResumeOrCreateRequest,
  SessionSendOptions,
  SessionEventListener,
  PermissionReply,
  PermissionRequestListener,
  SessionPermissionRequest,
  SessionPermissionRequestOption,
} from "./client.ts";

export type { InspectorUrlOptions } from "./inspector.ts";

export { InMemorySessionPersistDriver } from "./types.ts";
export type { SandboxProvider } from "./providers/types.ts";

export type {
  AcpEnvelope,
  AcpServerInfo,
  AcpServerListResponse,
  AgentInfo,
  AgentQuery,
  AgentInstallRequest,
  AgentInstallResponse,
  AgentListResponse,
  DesktopActionResponse,
  DesktopDisplayInfoResponse,
  DesktopErrorInfo,
  DesktopKeyboardDownRequest,
  DesktopKeyboardUpRequest,
  DesktopKeyModifiers,
  DesktopKeyboardPressRequest,
  DesktopKeyboardTypeRequest,
  DesktopMouseButton,
  DesktopMouseClickRequest,
  DesktopMouseDownRequest,
  DesktopMouseDragRequest,
  DesktopMouseMoveRequest,
  DesktopMousePositionResponse,
  DesktopMouseScrollRequest,
  DesktopMouseUpRequest,
  DesktopProcessInfo,
  DesktopRecordingInfo,
  DesktopRecordingListResponse,
  DesktopRecordingStartRequest,
  DesktopRecordingStatus,
  DesktopRegionScreenshotQuery,
  DesktopResolution,
  DesktopScreenshotFormat,
  DesktopScreenshotQuery,
  DesktopStartRequest,
  DesktopState,
  DesktopStatusResponse,
  DesktopStreamStatusResponse,
  DesktopWindowInfo,
  DesktopWindowListResponse,
  FsActionResponse,
  FsDeleteQuery,
  FsEntriesQuery,
  FsEntry,
  FsMoveRequest,
  FsMoveResponse,
  FsPathQuery,
  FsStat,
  FsUploadBatchQuery,
  FsUploadBatchResponse,
  FsWriteResponse,
  HealthResponse,
  InMemorySessionPersistDriverOptions,
  ListEventsRequest,
  ListPage,
  ListPageRequest,
  McpConfigQuery,
  McpServerConfig,
  ProblemDetails,
  ProcessConfig,
  ProcessCreateRequest,
  ProcessInfo,
  ProcessInputRequest,
  ProcessInputResponse,
  ProcessListQuery,
  ProcessListResponse,
  ProcessLogEntry,
  ProcessLogsQuery,
  ProcessLogsResponse,
  ProcessOwner,
  ProcessLogsStream,
  ProcessRunRequest,
  ProcessRunResponse,
  ProcessSignalQuery,
  ProcessState,
  ProcessTerminalClientFrame,
  ProcessTerminalErrorFrame,
  ProcessTerminalExitFrame,
  ProcessTerminalReadyFrame,
  ProcessTerminalResizeRequest,
  ProcessTerminalResizeResponse,
  ProcessTerminalServerFrame,
  SessionEvent,
  SessionPersistDriver,
  SessionRecord,
  SkillsConfig,
  SkillsConfigQuery,
  TerminalErrorStatus,
  TerminalExitStatus,
  TerminalReadyStatus,
  TerminalResizePayload,
  TerminalStatusMessage,
} from "./types.ts";

export type {
  SandboxAgentSpawnLogMode,
  SandboxAgentSpawnOptions,
} from "./spawn.ts";

export type {
  SpritesProviderOptions,
  SpritesCreateOverrides,
  SpritesClientOverrides,
} from "./providers/sprites.ts";
