// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  entries: [
    {
      idx: 0,
      when: 1773446400000,
      tag: "0000_auth_user",
      breakpoints: true,
    },
    {
      idx: 1,
      when: 1773532800000,
      tag: "0001_user_task_state",
      breakpoints: true,
    },
  ],
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`user\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`auth_user_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`email\` text NOT NULL,
	\`email_verified\` integer NOT NULL,
	\`image\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	CONSTRAINT \`user_singleton_id_check\` CHECK(\`id\` = 1)
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`user_auth_user_id_idx\` ON \`user\` (\`auth_user_id\`);
--> statement-breakpoint
CREATE TABLE \`session\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`token\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`ip_address\` text,
	\`user_agent\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`session_token_idx\` ON \`session\` (\`token\`);
--> statement-breakpoint
CREATE TABLE \`account\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`account_id\` text NOT NULL,
	\`provider_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`access_token\` text,
	\`refresh_token\` text,
	\`id_token\` text,
	\`access_token_expires_at\` integer,
	\`refresh_token_expires_at\` integer,
	\`scope\` text,
	\`password\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`account_provider_account_idx\` ON \`account\` (\`provider_id\`, \`account_id\`);
--> statement-breakpoint
CREATE TABLE \`user_profiles\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`github_account_id\` text,
	\`github_login\` text,
	\`role_label\` text NOT NULL,
	\`default_model\` text DEFAULT 'gpt-5.3-codex' NOT NULL,
	\`eligible_organization_ids_json\` text NOT NULL,
	\`starter_repo_status\` text NOT NULL,
	\`starter_repo_starred_at\` integer,
	\`starter_repo_skipped_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	CONSTRAINT \`user_profiles_singleton_id_check\` CHECK(\`id\` = 1)
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`user_profiles_user_id_idx\` ON \`user_profiles\` (\`user_id\`);
--> statement-breakpoint
CREATE TABLE \`session_state\` (
	\`session_id\` text PRIMARY KEY NOT NULL,
	\`active_organization_id\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);`,
    m0001: `CREATE TABLE \`user_task_state\` (
	\`task_id\` text NOT NULL,
	\`session_id\` text NOT NULL,
	\`active_session_id\` text,
	\`unread\` integer DEFAULT 0 NOT NULL,
	\`draft_text\` text DEFAULT '' NOT NULL,
	\`draft_attachments_json\` text DEFAULT '[]' NOT NULL,
	\`draft_updated_at\` integer,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`task_id\`, \`session_id\`)
);`,
  } as const,
};
