// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  entries: [
    {
      idx: 0,
      when: 1773376223815,
      tag: "0000_fluffy_kid_colt",
      breakpoints: true,
    },
    {
      idx: 1,
      when: 1773376223816,
      tag: "0001_add_repo_id",
      breakpoints: true,
    },
  ],
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`events\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`task_id\` text,
	\`branch_name\` text,
	\`kind\` text NOT NULL,
	\`payload_json\` text NOT NULL,
	\`created_at\` integer NOT NULL
);
`,
    m0001: `ALTER TABLE \`events\` ADD COLUMN \`repo_id\` text;
`,
  } as const,
};
